// <auto-generated />
namespace WebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixPlease : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixPlease));
        
        string IMigrationMetadata.Id
        {
            get { return "201505110339513_FixPlease"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
